local L = AceLibrary("AceLocale-2.2"):new("ReagentFu");

L:RegisterTranslations("enUS", function() return {
	["Keeps track of your reagents for buffing."] = true,
	
	["Show short names"] = true,
	["Show short reagent names in FuBar text"] = true,
	["Reagents"] = true,
	
	-- reagents
	--mage	
	["Arcane Powder"] = true,
	["Arcane Powder.SHORT"] = "Powder: ",
	["Rune of Teleportation"] = true,
	["Rune of Teleportation.SHORT"] = "Teleport: ",
	["Rune of Portals"] = true,
	["Rune of Portals.SHORT"] = "Portal: ",
	["Light Feather"] = true,
	["Light Feather.SHORT"] = "Feather: ",
	--priest
	["Holy Candle"] = true,
	["Holy Candle.SHORT"] = "Holy: ",
	["Sacred Candle"] = true,
	["Sacred Candle.SHORT"] = "Sacred: ",
	["Devout Candle"] = true,
	["Devout Candle.SHORT"] = "Devout :",
	-- rogue
	["Thistle Tea"] = true,
	["Thistle Tea.SHORT"] = "Tea: ",
	["Instant Poison"] = true,
	["Deadly Poison"] = true,
	["Crippling Poison"] = true,
	["Mind-numbing Poison"] = true,
	["Wound Poison"] = true,
	["Anesthetic Poison"] = true,
	["Poison: "] = true,
	--druid
	["Wild Berries"] = true,
	["Wild Berries.SHORT"] = "Berry: ",
	["Wild Thornroot"] = true,
	["Wild Thornroot.SHORT"] = "Thornroot: ",
	["Wild Quillvine"] = true,
	["Wild Quillvine.SHORT"] = "Quillvine: ",
	["Maple Seed"] = true,
	["Maple Seed.SHORT"] = "Maple: ",
	["Stranglethorn Seed"] = true,
	["Stranglethorn Seed.SHORT"] = "Stranglethorn: ",
	["Ashwood Seed"] = true,
	["Ashwood Seed.SHORT"] = "Ashwood: ",
	["Hornbeam Seed"] = true,
	["Hornbeam Seed.SHORT"] = "Hornbeam: ",
	["Ironwood Seed"] = true,
	["Ironwood Seed.SHORT"] = "Ironwood: ",
	["Flintweed Seed"] = true,
	["Flintweed Seed.SHORT"] = "Flintweed: ",
	["Starleaf Seed"] = true,
  ["Starleaf Seed.SHORT"] = "Starleaf: ",
	["Wild Spineleaf"] = true,
	["Wild Spineleaf.SHORT"] = "Spineleaf: ",
	-- Paladin
	["Symbol of Divinity"] = true,
	["Symbol of Divinity.SHORT"] = "Divinity: ",
	["Symbol of Kings"] = true,
	["Symbol of Kings.SHORT"] = "Kings: ",
	-- Shaman
	["Ankh"] = true,
	["Ankh.SHORT"] = "Ankh: ",
	["Shiny Fish Scales"] = true,
	["Shiny Fish Scales.SHORT"] = "Scales: ",
	["Fish Oil"] = true,
	["Fish Oil.SHORT"] = "Oil: ",
	-- warlock
	["Soul Shard"] = true,
	["Soul Shard.SHORT"] = "Shard: ",
	["Healthstone"] = true,
	["Healthstone.SHORT"] = "HS: ",
	["Soulstone"] = true,
	["Soulstone.SHORT"] = "SS: ",
	["Spellstone"] = true,
	["Spellstone.SHORT"] = "Spell: ",
	["Firestone"] = true,
	["Firestone.SHORT"] = "Fire: ",
	["Infernal Stone"] = true,
	["Infernal Stone.SHORT"] = "Infernal: ",
	["Demonic Figurine"] = true,
	["Demonic Figurine.SHORT"] = "Demonic: ",
  -- death knight
	["Corpse Dust"] = true,
	["Corpse Dust.SHORT"] = "Dust: ",	
    -- hunter, rogue, warrior
    ["Arrow"] = true,
    ["Arrow.SHORT"] = "-> ",
    ["Bullet"] = true,
    ["Bullet.SHORT"] = "* ",
} end)