local L = AceLibrary("AceLocale-2.2"):new("ReagentFu");

L:RegisterTranslations("deDE", function() return {
  ["Keeps track of your reagents for buffing."] = "Verschafft einen \195\156berblick \195\188ber die Reagenzien f\195\188r das Wirken von Zaubern.",

  ["Show short names"] = "Kurze Namen anzeigen",
  ["Show short reagent names in FuBar text"] = "Kurze Reagenziennamen im FuBar-Text anzeigen",
  ["Reagents"] = "Reagenzien",

  -- reagents
  --mage
  ["Arcane Powder"] = "Arkanes Pulver",
  ["Arcane Powder.SHORT"] = "Pulver: ",
  ["Rune of Teleportation"] = "Rune der Teleportation",
  ["Rune of Teleportation.SHORT"] = "Teleport: ",
  ["Rune of Portals"] = "Rune der Portale",
  ["Rune of Portals.SHORT"] = "Portal: ",
  ["Light Feather"] = "Leichte Feder",
  ["Light Feather.SHORT"] = "Feder: ",
  --priest
  ["Holy Candle"] = "Heilige Kerze",
  ["Holy Candle.SHORT"] = "Heilige: ",
  ["Sacred Candle"] = "Hochheilige Kerze",
  ["Sacred Candle.SHORT"] = "Hochheilige: ",
  ["Devout Candle"] = "Andachtskerze",
	["Devout Candle.SHORT"] = "Andachts: ",
  -- rogue
  ["Thistle Tea"] = "Disteltee",
  ["Thistle Tea.SHORT"] = "Distel: ",
  ["Instant Poison"] = "Sofort wirkendes Gift",
  ["Deadly Poison"] = "T\195\182dliches Gift",
  ["Crippling Poison"] = "Verkr\195\188ppelndes Gift",
  ["Mind-numbing Poison"] = "Gedankenbenebelndes Gift",
  ["Wound Poison"] = "Wundgift",
  ["Anesthetic Poison"] = "Beruhigendes Gift",
  ["Poison: "] = "Gift: ",
  --druid
  ["Wild Berries"] = "Wilde Beeren",
  ["Wild Berries.SHORT"] = "Beeren: ",
  ["Wild Thornroot"] = "Wilder Dornwurz",
  ["Wild Thornroot.SHORT"] = "Dornwurz: ",
  ["Wild Quillvine"] = "Wilde Federranke",
  ["Wild Quillvine.SHORT"] = "Federranke: ",
  ["Maple Seed"] = "Ahornsamenkorn",
  ["Maple Seed.SHORT"] = "Ahornholz: ",
  ["Stranglethorn Seed"] = "Schlingendornsamenkorn",
  ["Stranglethorn Seed.SHORT"] = "Schlingendorn: ",
  ["Ashwood Seed"] = "Eschenholzsamenkorn",
  ["Ashwood Seed.SHORT"] = "Eschenholz: ",
  ["Hornbeam Seed"] = "Hainbuchensamenkorn",
  ["Hornbeam Seed.SHORT"] = "Hainbuchen: ",
  ["Ironwood Seed"] = "Eisenholzsamenkorn",
  ["Ironwood Seed.SHORT"] = "Eisenholz: ",
  ["Flintweed Seed"] = "Flintgrassaat",
  ["Flintweed Seed.SHORT"] = "Flintgras: ",
  ["Starleaf Seed"] = "Sternblattsamen",
  ["Starleaf Seed.SHORT"] = "Sternblatt: ",
	["Wild Spineleaf"] = "Wildes Wirbelkraut",
	["Wild Spineleaf.SHORT"] = "Wirbelkraut: ",
  -- Paladin
  ["Symbol of Divinity"] = "Symbol der Offenbarung",
  ["Symbol of Divinity.SHORT"] = "Offenb.: ",
  ["Symbol of Kings"] = "Symbol der K\195\182nige",
  ["Symbol of Kings.SHORT"] = "K\195\182nige: ",
  -- Shaman
  ["Ankh"] = "Ankh",
  ["Ankh.SHORT"] = "Ankh: ",
  ["Shiny Fish Scales"] = "Gl\195\164nzende Fischschuppen",
  ["Shiny Fish Scales.SHORT"] = "Schuppen: ",
  ["Fish Oil"] = "Fisch\195\182l",
  ["Fish Oil.SHORT"] = "\195\150l: ",
  -- warlock
  ["Soul Shard"] = "Seelensplitter",
  ["Soul Shard.SHORT"] = "Splitter: ",
  ["Healthstone"] = "Gesundheitsstein",
  ["Healthstone.SHORT"] = "Gesundheitsstein: ",
  ["Soulstone"] = "Seelenstein",
  ["Soulstone.SHORT"] = "Seelen: ",
  ["Spellstone"] = "Zauberstein",
  ["Spellstone.SHORT"] = "Zauber: ",
  ["Firestone"] = "Feuerstein",
  ["Firestone.SHORT"] = "Feuer: ",
  ["Infernal Stone"] = "H\195\182llenstein",
  ["Infernal Stone.SHORT"] = "H\195\182llen: ",
  ["Demonic Figurine"] = "D\195\164monenstatuette",
  ["Demonic Figurine.SHORT"] = "Statuette: ",
  -- death knight
	["Corpse Dust"] = "Leichenstaub",
	["Corpse Dust.SHORT"] = "Staub: ",
	   -- hunter, rogue, warrior
  ["Arrow"] = "Pfeil",
  ["Arrow.SHORT"] = "-> ",
  ["Bullet"] = "Kugel",
  ["Bullet.SHORT"] = "* ",
} end)