local L = AceLibrary("AceLocale-2.2"):new("ReagentFu");

L:RegisterTranslations("zhCN", function() return {

	-- General
	["Keeps track of your reagents for buffing."] = "监视你的施法材料数量。",
	["Show short names"] = "显示简称",
	["Show short reagent names in FuBar text"] = "在 FuBar 上显示施法材料的简称。",
	["Reagents"] = "施法材料",

	-- reagents
	--mage	
	["Arcane Powder"] = "魔粉",
	["Arcane Powder.SHORT"] = "粉:",
	["Rune of Teleportation"] = "传送符文",
	["Rune of Teleportation.SHORT"] = "传:",
	["Rune of Portals"] = "传送门符文",
	["Rune of Portals.SHORT"] = "门:",
	["Light Feather"] = "轻羽毛",
	["Light Feather.SHORT"] = "羽:",
	--priest
	["Holy Candle"] = "圣洁蜡烛",
	["Holy Candle.SHORT"] = "圣:",
	["Sacred Candle"] = "神圣蜡烛",
	["Sacred Candle.SHORT"] = "神:",
	["Devout Candle"] = "Devout Candle",
	["Devout Candle.SHORT"] = "Devout :",
	-- rogue
	["Thistle Tea"] = "菊花茶",
	["Thistle Tea.SHORT"] = "茶:",
	["Instant Poison"] = "速效药膏",
	["Deadly Poison"] = "致命药膏",
	["Crippling Poison"] = "致残药膏",
	["Mind-numbing Poison"] = "麻痹药膏",
	["Wound Poison"] = "致伤药膏",
	["Poison: "] = "毒:",
	["Anesthetic Poison"] = "Anesthetic Poison",
	--druid
	["Wild Berries"] = "野生浆果",
	["Wild Berries.SHORT"] = "浆:",
	["Wild Thornroot"] = "野生棘根草",
	["Wild Thornroot.SHORT"] = "棘:",
	["Wild Quillvine"] = "野生刺藤",
	["Wild Quillvine.SHORT"] = "藤:",
	["Maple Seed"] = "枫树种子",
	["Maple Seed.SHORT"] = "枫:",
	["Stranglethorn Seed"] = "荆棘种子",
	["Stranglethorn Seed.SHORT"] = "荆:",
	["Ashwood Seed"] = "灰木种子",
	["Ashwood Seed.SHORT"] = "灰:",
	["Hornbeam Seed"] = "角树种子",
	["Hornbeam Seed.SHORT"] = "角:",
	["Ironwood Seed"] = "铁木种子",
	["Ironwood Seed.SHORT"] = "铁:",
	["Flintweed Seed"] = "灼草种子",
	["Flintweed Seed.SHORT"] = "灼:",
	["Starleaf Seed"] = "Starleaf Seed",
	["Starleaf Seed.SHORT"] = "Starleaf: ",
	["Wild Spineleaf"] = "Wild Spineleaf",
	["Wild Spineleaf.SHORT"] = "Spineleaf: ",
	-- Paladin
	["Symbol of Divinity"] = "神圣符印",
	["Symbol of Divinity.SHORT"] = "神:",
	["Symbol of Kings"] = "王者印记",
	["Symbol of Kings.SHORT"] = "王:",
	-- Shaman
	["Ankh"] = "十字章",
	["Ankh.SHORT"] = "章:",
	["Shiny Fish Scales"] = "闪亮的鱼鳞",
	["Shiny Fish Scales.SHORT"] = "鳞:",
	["Fish Oil"] = "鱼油",
	["Fish Oil.SHORT"] = "油:",
	-- warlock
	["Soul Shard"] = "灵魂碎片",
	["Soul Shard.SHORT"] = "碎:",
	["Healthstone"] = "治疗石",
	["Healthstone.SHORT"] = "治:",
	["Soulstone"] = "灵魂石",
	["Soulstone.SHORT"] = "魂:",
	["Spellstone"] = "法術石",
	["Spellstone.SHORT"] = "法:",
	["Firestone"] = "火焰石",
	["Firestone.SHORT"] = "火:",
	["Infernal Stone"] = "地狱火石",
	["Infernal Stone.SHORT"] = "狱:",
	["Demonic Figurine"] = "恶魔雕像",
	["Demonic Figurine.SHORT"] = "恶:",
	-- death knight
	["Corpse Dust"] = "Corpse Dust",
	["Corpse Dust.SHORT"] = "Dust: ",
    -- hunter, rogue, warrior
    ["Arrow"] = "箭",
    ["Arrow.SHORT"] = "-> ",
    ["Bullet"] = "子弹",
    ["Bullet.SHORT"] = "* ",

} end)