local L = AceLibrary("AceLocale-2.2"):new("ReagentFu");

L:RegisterTranslations("zhCN", function() return {
	["Keeps track of your reagents for buffing."] = "監視你的施法材料數量。",
	
	["Show short names"] = "顯示簡稱",
	["Show short reagent names in FuBar text"] = "在 FuBar 上顯示施法材料的簡稱。",
	["Reagents"] = "施法材料",

	-- reagents
	--mage	
	["Arcane Powder"] = "魔粉",
	["Arcane Powder.SHORT"] = "粉:",
	["Rune of Teleportation"] = "傳送符文",
	["Rune of Teleportation.SHORT"] = "傳:",
	["Rune of Portals"] = "傳送門符文",
	["Rune of Portals.SHORT"] = "門:",
	["Light Feather"] = "輕羽毛",
	["Light Feather.SHORT"] = "羽:",
	--priest
	["Holy Candle"] = "聖潔蠟燭",
	["Holy Candle.SHORT"] = "聖:",
	["Sacred Candle"] = "神聖蠟燭",
	["Sacred Candle.SHORT"] = "神:",
	-- rogue
	["Flash Powder"] = "閃光粉",
	["Flash Powder.SHORT"] = "閃:",
	["Blinding Powder"] = "致盲粉",
	["Blinding Powder.SHORT"] = "盲:",
	["Thistle Tea"] = "菊花茶",
	["Thistle Tea.SHORT"] = "茶:",
	["Instant Poison"] = "速效毒藥",
	["Deadly Poison"] = "致命毒藥",
	["Crippling Poison"] = "致殘毒藥",
	["Mind-numbing Poison"] = "麻痹毒藥",
	["Wound Poison"] = "致傷毒藥",
	["Poison: "] = "毒:",
	--druid
	["Wild Berries"] = "野生漿果",
	["Wild Berries.SHORT"] = "漿:",
	["Wild Thornroot"] = "野生棘根草",
	["Wild Thornroot.SHORT"] = "棘:",
	["Wild Quillvine"] = "野生羽蔓",
	["Wild Quillvine.SHORT"] = "羽:",
	["Maple Seed"] = "楓樹種子",
	["Maple Seed.SHORT"] = "楓:",
	["Stranglethorn Seed"] = "荊棘種子",
	["Stranglethorn Seed.SHORT"] = "荊:",
	["Ashwood Seed"] = "灰木種子",
	["Ashwood Seed.SHORT"] = "灰:",
	["Hornbeam Seed"] = "角樹種子",
	["Hornbeam Seed.SHORT"] = "角:",
	["Ironwood Seed"] = "鐵木種子",
	["Ironwood Seed.SHORT"] = "鐵:",
	["Flintweed Seed"] = "火石草種子",
	["Flintweed Seed.SHORT"] = "火:",
	-- Paladin
	["Symbol of Divinity"] = "神聖符印",
	["Symbol of Divinity.SHORT"] = "神:",
	["Symbol of Kings"] = "王者印記",
	["Symbol of Kings.SHORT"] = "王:",
	-- Shaman
	["Ankh"] = "十字章",
	["Ankh.SHORT"] = "章:",
	["Shiny Fish Scales"] = "閃亮的魚鱗",
	["Shiny Fish Scales.SHORT"] = "鱗:",
	["Fish Oil"] = "魚油",
	["Fish Oil.SHORT"] = "油:",
	-- warlock
	["Soul Shard"] = "靈魂裂片",
	["Soul Shard.SHORT"] = "碎:",
	["Healthstone"] = "治療石",
	["Healthstone.SHORT"] = "治:",
	["Soulstone"] = "靈魂石",
	["Soulstone.SHORT"] = "魂:",
	["Spellstone"] = "法術石",
	["Spellstone.SHORT"] = "法:",
	["Firestone"] = "火焰石",
	["Firestone.SHORT"] = "火:",
	["Infernal Stone"] = "地獄火石",
	["Infernal Stone.SHORT"] = "獄:",
	["Demonic Figurine"] = "惡魔雕像",
	["Demonic Figurine.SHORT"] = "惡:",
    -- hunter, rogue, warrior
    ["Arrow"] = "箭",
    ["Arrow.SHORT"] = "-> ",
    ["Bullet"] = "子彈",
    ["Bullet.SHORT"] = "* ",
} end)
