local L = AceLibrary("AceLocale-2.2"):new("ReagentFu");

L:RegisterTranslations("ruRU", function() return {
  ["Keeps track of your reagents for buffing."] = "Следит за количеством реагентов для баффов.",

  ["Show short names"] = "Показывать короткие имена",
  ["Show short reagent names in FuBar text"] = "Показывать короткие имена в тексте FuBar",
  ["Reagents"] = "Реагенты",

  -- reagents
  --mage
  ["Arcane Powder"] = "Порошок чар",
  ["Arcane Powder.SHORT"] = "Порошок: ",
  ["Rune of Teleportation"] = "Руна телепортации",
  ["Rune of Teleportation.SHORT"] = "Телепорт: ",
  ["Rune of Portals"] = "Руна порталов",
  ["Rune of Portals.SHORT"] = "Портал: ",
  ["Light Feather"] = "Leichte Feder",
  ["Light Feather.SHORT"] = "Feder: ",
  --priest
  ["Holy Candle"] = "Святая свеча",
  ["Holy Candle.SHORT"] = "Свеча: ",
  ["Sacred Candle"] = "Священная свеча",
  ["Sacred Candle.SHORT"] = "Святая свеча: ",
  -- rogue
  ["Flash Powder"] = "Blitzstrahlpulver",
  ["Flash Powder.SHORT"] = "Blitz: ",
  ["Blinding Powder"] = "Blendungspulver",
  ["Blinding Powder.SHORT"] = "Blend: ",
  ["Thistle Tea"] = "Disteltee",
  ["Thistle Tea.SHORT"] = "Distel: ",
  ["Instant Poison"] = "Sofort wirkendes Gift",
  ["Deadly Poison"] = "T\195\182dliches Gift",
  ["Crippling Poison"] = "Verkr\195\188ppelndes Gift",
  ["Mind-numbing Poison"] = "Gedankenbenebelndes Gift",
  ["Wound Poison"] = "Wundgift",
  ["Poison: "] = "Яд: ",
  --druid
  ["Wild Berries"] = "Лесные ягоды",
  ["Wild Berries.SHORT"] = "Ягоды: ",
  ["Wild Thornroot"] = "Дикий шипокорень",
  ["Wild Thornroot.SHORT"] = "Шипокорень: ",
  ["Wild Quillvine"] = "Дикая перьелоза",
  ["Wild Quillvine.SHORT"] = "Перьелоза: ",
  ["Maple Seed"] = "Семена клена",
  ["Maple Seed.SHORT"] = "Клен: ",
  ["Stranglethorn Seed"] = "Семя из Тернистой долины",
  ["Stranglethorn Seed.SHORT"] = "Тернист: ",
  ["Ashwood Seed"] = "Семена ясеня",
  ["Ashwood Seed.SHORT"] = "Ясень: ",
  ["Hornbeam Seed"] = "Семена граба",
  ["Hornbeam Seed.SHORT"] = "Граб: ",
  ["Ironwood Seed"] = "Семена железного дерева",
  ["Ironwood Seed.SHORT"] = "Железн: ",
  ["Flintweed Seed"] = "Семена кремень-травы",
  ["Flintweed Seed.SHORT"] = "Кремень: ",
  -- Paladin
  ["Symbol of Divinity"] = "Символ божественности",
  ["Symbol of Divinity.SHORT"] = "Божеств.: ",
  ["Symbol of Kings"] = "Символ королей",
  ["Symbol of Kings.SHORT"] = "Королей: ",
  -- Shaman
  ["Ankh"] = "Крест",
  ["Ankh.SHORT"] = "Крест: ",
  ["Shiny Fish Scales"] = "Gl\195\164nzende Fischschuppen",
  ["Shiny Fish Scales.SHORT"] = "Schuppen: ",
  ["Fish Oil"] = "Fisch\195\182l",
  ["Fish Oil.SHORT"] = "\195\150l: ",
  -- warlock
  ["Soul Shard"] = "Seelensplitter",
  ["Soul Shard.SHORT"] = "Splitter: ",
  ["Healthstone"] = "Gesundheitsstein",
  ["Healthstone.SHORT"] = "Gesundheitsstein: ",
  ["Soulstone"] = "Seelenstein",
  ["Soulstone.SHORT"] = "Seelen: ",
  ["Spellstone"] = "Zauberstein",
  ["Spellstone.SHORT"] = "Zauber: ",
  ["Firestone"] = "Feuerstein",
  ["Firestone.SHORT"] = "Feuer: ",
  ["Infernal Stone"] = "Камень инфернала",
  ["Infernal Stone.SHORT"] = "Инфернал: ",
  ["Demonic Figurine"] = "Демоническая статуэтка",
  ["Demonic Figurine.SHORT"] = "Статуэтка: ",
   -- hunter, rogue, warrior
  ["Arrow"] = "Стрелы",
  ["Arrow.SHORT"] = "-> ",
  ["Bullet"] = "Пули",
  ["Bullet.SHORT"] = "* ",
} end)
